name: CI and Deployment Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # Job 1: Construction des images Docker
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_API_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}

      - name: Build frontend Docker image
        run: docker build ./frontend -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/frontend:latest

      - name: Push frontend Docker image
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/frontend:latest

      - name: Build backend Docker image
        run: docker build ./backend -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/backend:latest

      - name: Push backend Docker image
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/backend:latest

  # Job 2: Déploiement sur le serveur distant
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Transfer docker-compose.yml to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER_IP }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          source: './docker-compose.yml'
          target: '/home/Jaures'

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER_IP }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          script: |
            echo "Déploiement des services sur le serveur distant..."
            cd /home/Jaures
            docker pull ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/frontend:latest
            docker pull ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/backend:latest
            
            # Arrête les anciens conteneurs et redémarre avec les nouvelles images
            docker-compose -f /home/Jaures/docker-compose.yml down || true
            docker-compose -f /home/Jaures/docker-compose.yml up -d
