name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_API_KEY }}
        registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}

      #Upload docker-compose.yml to server scaleway
    - name: Upload docker-compose.yml to Scaleway
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SCALEWAY_HOST }}
        username: ${{ secrets.SCALEWAY_USER }}
        key: ${{ secrets.SCALEWAY_SSH_KEY }}
        source: "."
        target: '/home/moise/'

    - name: Build the webserver Docker image
      run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/groupe-2/webserver:latest

    - name: Push the webserver Docker image to scaleway
      run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/groupe-2/webserver:latest

    - name: Build the scheduler Docker image
      run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/groupe-2/scheduler:latest

    - name: Push the scheduler Docker image to scaleway
      run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/groupe-2/scheduler:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build-images
    steps:

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SCALEWAY_HOST }}
        username: ${{ secrets.SCALEWAY_USER }}
        key: ${{ secrets.SCALEWAY_SSH_KEY }}
        port: 22
        script: |
          cd /home/moise
          docker-compose down || true
          docker-compose rm -f || true
          docker pull ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/groupe-2/webserver:latest
          docker pull ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/groupe-2/scheduler:latest
          docker-compose up -d
          echo 'good job'





